linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/go-kit/log.Logger).Log
      - (*encoding/json.Encoder).Encode

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - errcheck
      text: 'Error return value of `client.Schema.Create` is not checked'
