version: '3.8'

services:
  conduit_api:
    image: conduit_api
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
