version: '3.8'

services:
  prometheus:
    container_name: realworld_prometheus_metrics
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always