# fly.toml file generated for realworld-go-kit on 2023-04-11T17:13:50-07:00

app = "realworld-go-kit"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[env]
PORT = "80"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
