version: '3'

dotenv: ['.env']

tasks:
  run:
    cmds:
      - DATABASE_URL=$DATABASE_URL PORT=$PORT go run ./cmd/conduit/main.go
  build:
    cmds:
      - go build -v -o ./realworld_go_kit ./cmd/conduit/main.go
  run-build:
    cmds:
      - ./realworld_go_kit
  format:
    cmds:
      - go fmt ./...
  vet:
    cmds:
      - go vet ./...
  lint:
    cmds:
      - golangci-lint --version

includes:
  docker:
    taskfile: ./Taskfile.docker.yml
    vars:
      DATABASE_URL: $DATABASE_URL
      PORT: $PORT
  db:
    taskfile: ./Taskfile.db.yml
    vars:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD