// Code generated by entc, DO NOT EDIT.

package follow

import (
	"time"
)

const (
	// Label holds the string label denoting the follow type in the database.
	Label = "follow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldFollowerID holds the string denoting the follower_id field in the database.
	FieldFollowerID = "follower_id"
	// FieldFolloweeID holds the string denoting the followee_id field in the database.
	FieldFolloweeID = "followee_id"
	// EdgeUserFollower holds the string denoting the user_follower edge name in mutations.
	EdgeUserFollower = "user_follower"
	// EdgeUserFollowee holds the string denoting the user_followee edge name in mutations.
	EdgeUserFollowee = "user_followee"
	// Table holds the table name of the follow in the database.
	Table = "follows"
	// UserFollowerTable is the table that holds the user_follower relation/edge.
	UserFollowerTable = "follows"
	// UserFollowerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserFollowerInverseTable = "users"
	// UserFollowerColumn is the table column denoting the user_follower relation/edge.
	UserFollowerColumn = "follower_id"
	// UserFolloweeTable is the table that holds the user_followee relation/edge.
	UserFolloweeTable = "follows"
	// UserFolloweeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserFolloweeInverseTable = "users"
	// UserFolloweeColumn is the table column denoting the user_followee relation/edge.
	UserFolloweeColumn = "followee_id"
)

// Columns holds all SQL columns for follow fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldFollowerID,
	FieldFolloweeID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
)
