name: Run integration tests

on:
  workflow_run:
    workflows: ['Build, test, and deploy']
    types:
      - completed

jobs:
  build:
    name: run CI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install task CLI
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Run CI tests
        run: task integration:production
